name: rust build

on:
  push:
    branches: [ dev, stable ] # CHANGE "master" TO "main" IF THAT IS THE NAME OF YOUR MAIN BRANCH!
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - 'scripts/**'
  pull_request:
    branches: [ dev, stable ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - 'scripts/**'
      

jobs:
  plugin_build:
    env:
      PLUGIN_NAME: hdr
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: checkout version
      uses: actions/checkout@v2
    - run: |
        PATH=$PATH:/root/.cargo/bin && cd scripts && python3 make_dist.py && cd ..
      env:
        HOME: /root
    - name: Upload hdr-switch artifact
      uses: actions/upload-artifact@v2
      with:
        name: hdr-switch
        path: distributions/hdr-switch.zip
    - name: Upload hdr-ryujinx artifact
      uses: actions/upload-artifact@v2
      with:
        name: hdr-ryujinx
        path: distributions/hdr-ryujinx.zip
  upload_nightly:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - plugin_build
    steps:
    - name: delete old betas
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tag_pattern: nightly # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Update Nightly
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: nightly
        name: nightly
        body: >
          Nightly built off of the latest code in the repository. 
        files: >
          hdr-switch/*
          hdr-ryujinx/*
  upload_beta:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    needs:
      - plugin_build
    steps:
    - name: delete old betas
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tag_pattern: beta # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Update Beta
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: beta
        name: beta
        body: >
          Beta built off of the latest code in the repository. 
        files: >
          hdr-switch/*
          hdr-ryujinx/*
