name: validate_semver

on:
  pull_request:
    branches: [ dev ]

        
jobs:
  # validate the PR title
  validate_semver:
    runs-on: ubuntu-latest
    steps:
    - uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: '(bugfix),(balance),(rework),(feature),(major)' # title should start with the given prefix
        prefix_case_sensitive: false # title prefix are case insensitive
  comment_bad_pr:
    runs-on: ubuntu-latest
    needs: [validate_semver]
    if: always() && (needs.validate_semver.result == 'failure')
    steps:
      - name: Comment Bad PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            This PR has no versioning info! Reopen this PR with a title that starts with one of the following options:\n
            (bugfix), (balance), (rework), (feature), or (major). \n
            Example title:
              (bugfix) Fix falling through the floor on training reset
  