name: comment failed check

on:
  workflow_run:
    workflows: ['validate_semver']
    types: [completed]

jobs:
  comment-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: quipper/comment-failure-action@v0.1.1