name: publish_lvd_nightly.yml

on:
  push:
    branches:
    - "lvd-actions"
  workflow_run:
    workflows: ["build_nightly"]
    types:
      - completed

jobs:
  # bump the version and build the changelog

  ##############  handle the creasion of the full package installation  ##############
  lvd_publish:
    runs-on: windows-latest
    steps:
    - name: checkout version
      uses: actions/checkout@v2

    - id: romfs_zip
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "HDR-Development/romfs-release"
        latest: true
        zipBall: true

    - id: yamlvd_exe
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "ultimate-research/lvd-rs"
        tag: v0.3.0
        fileName: "yamlvd.exe"

    - name: lvd_to_yml
      run: |
        7z x romfs.zip
        mkdir yml
        python3 scripts/lvd-to-yml.py ./yamlvd.exe ./ultimate/mods/hdr-stages/stage ./
        ls -R

    - name: Push lvd file to Suddy's HDRStageTools
      uses: nkoppel/push-files-to-another-repository@v1.1.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB_HDRSTAGETOOL }}
      with:
        source-files: './lvd.zip'
        destination-username: 'SuddyN'
        destination-repository: 'HDRStageTools'
        destination-branch: 'gh-pages'
        destination-directory: 'nightly'
        commit-username: 'SuddyN'
        commit-email: 'suddy121800@hotmail.com'
