name: nightly build

on:
  push:
    branches: [ dev ] # CHANGE "master" TO "main" IF THAT IS THE NAME OF YOUR MAIN BRANCH!
  #pull_request:
  #  branches: [ dev ]
  #workflow_dispatch:

jobs:
  plugin:
    env:
      PLUGIN_NAME: hdr # CHANGE THIS TO THE NAME OF YOUR TEMPLATE!
    runs-on: ubuntu-latest
    container: 
      image: jugeeya/cargo-skyline:2.1.0
    steps:
    - uses: actions/checkout@v2
    - name: Build release NRO
      run: |
        PATH=$PATH:/root/.cargo/bin && cd plugin && /root/.cargo/bin/cargo-skyline skyline build --release && cd ..
      env:
        HOME: /root
    - name: Upload plugin artifact
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: plugin/target/aarch64-skyline-switch/release/lib${{env.PLUGIN_NAME}}.nro
  upload:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    needs:
      - plugin
    steps:
    - name: delete old betas
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tag_pattern: nightly # defaults to ""
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Update Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: nightly
        name: nightly
        body: >
          Nightly built off of the latest code in the repository. 
        files: >
          plugin/* 
